# Generated by Django 3.2.5 on 2021-07-31 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0002_banks_requestedblood_requestnoblood'),
    ]

    operations = [
        migrations.AddField(
            model_name='donner',
            name='Bid',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='BankApp.banks'),
            preserve_default=False,
        ),
    ]
