# Generated by Django 3.2.5 on 2021-07-31 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0003_donner_bid'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedblood',
            name='Secret',
            field=models.CharField(default='SGN1ONS', max_length=100),
            preserve_default=False,
        ),
    ]
