# Generated by Django 3.2.5 on 2021-07-31 20:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BankApp', '0004_requestedblood_secret'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BloodGrp', models.CharField(max_length=20)),
                ('Secret', models.CharField(max_length=100)),
                ('Bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BankApp.banks')),
                ('Did', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
