# Generated by Django 3.2.5 on 2021-07-31 21:45

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('BankApp', '0006_requestedblood_bloodid'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donner',
            new_name='DonnerModel',
        ),
        migrations.RenameModel(
            old_name='Requester',
            new_name='RequesterModel',
        ),
    ]
