# Generated by Django 3.2.5 on 2021-08-01 07:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0008_blood_is_available'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='BState',
            new_name='Bstate',
        ),
    ]
