# Generated by Django 3.2.5 on 2021-08-01 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('BankApp', '0009_rename_bstate_banks_bstate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='banks',
            old_name='Bstate',
            new_name='BState',
        ),
    ]
